mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection ACMnews --type json --file allTime/ResultsACM.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection ACMnews --type json --out allTime/ResultsACM.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection KKMnews --type json --file allTime/ResultsAllKKM.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection KKMnews --type json --out allTime/ResultsAllKKM.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Bakkersnews --type json --file allTime/ResultsBakkers.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Bakkersnews --type json --out allTime/ResultsBakkers.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Bakkerswereldnews --type json --file allTime/ResultsBakkerswereld.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Bakkerswereldnews --type json --out allTime/ResultsBakkerswereld.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Ceresnews --type json --file allTime/ResultsCeres.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Ceresnews --type json --out allTime/ResultsCeres.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Dosschenews --type json --file allTime/ResultsDossche.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Dosschenews --type json --out allTime/ResultsDossche.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Souffletnews --type json --file allTime/ResultsSoufflet.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection Souffletnews --type json --out allTime/ResultsSoufflet.json

mongoimport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection TIJDnews --type json --file allTime/ResultsTijd.json
mongoexport --host ScrapedNews-shard-0/scrapednews-shard-00-00-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-01-3zys9.azure.mongodb.net:27017,scrapednews-shard-00-02-3zys9.azure.mongodb.net:27017 --ssl --username serverUser --password XXXXX --authenticationDatabase admin --db KKMdata --collection TIJDnews --type json --out allTime/ResultsTijd.json

python3 databaseUnique.py